apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-image-source-idfd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-image-source-idfd
    app.kubernetes.io/part-of: test-app-bnge
  name: build-suite-test-component-image-source-idfd
  namespace: e2e-test-kkot
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-component-image-source-idfd
status:
  loadBalancer: {}
